var myFullName;
console.log(myFullName);
myFullName="Komal Dhone";
console.log("Inetial Value:",myFullName);
myFullName="Komal Vitthal Dhone";
console.log("Updated Value:",myFullName);
 var myLove="I Love Only Js";
 console.log(myLove);
 var firstName="Komal";
 var lastName="Dhone";
 var age="25";
 var address="pandharpur";
 var pin_code="413304";
 var gender="Female";
 var is_married="Yes";
 console.log("details:-", firstName,lastName,age,address,pin_code,gender,is_married);